services:
  vpn-exit-node:
    container_name: vpn-exit-node
    hostname: vpn-exit-node
    build:
      dockerfile: ./Dockerfile
    environment:
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY}
      - HTTP_PORT=${HTTP_PORT}
    restart: unless-stopped
